/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteResponse
 */
export interface DeleteResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteResponse
     */
    wasAcknowledged: boolean;
    /**
     * 
     * @type {number}
     * @memberof DeleteResponse
     */
    deletedCount: number;
}

/**
 * Check if a given object implements the DeleteResponse interface.
 */
export function instanceOfDeleteResponse(value: object): value is DeleteResponse {
    if (!('wasAcknowledged' in value) || value['wasAcknowledged'] === undefined) return false;
    if (!('deletedCount' in value) || value['deletedCount'] === undefined) return false;
    return true;
}

export function DeleteResponseFromJSON(json: any): DeleteResponse {
    return DeleteResponseFromJSONTyped(json, false);
}

export function DeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'wasAcknowledged': json['wasAcknowledged'],
        'deletedCount': json['deletedCount'],
    };
}

export function DeleteResponseToJSON(json: any): DeleteResponse {
    return DeleteResponseToJSONTyped(json, false);
}

export function DeleteResponseToJSONTyped(value?: DeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wasAcknowledged': value['wasAcknowledged'],
        'deletedCount': value['deletedCount'],
    };
}

