/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndexDropResponse
 */
export interface IndexDropResponse {
    /**
     * 
     * @type {boolean}
     * @memberof IndexDropResponse
     */
    dropped: boolean;
}

/**
 * Check if a given object implements the IndexDropResponse interface.
 */
export function instanceOfIndexDropResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dropped" in value;

    return isInstance;
}

export function IndexDropResponseFromJSON(json: any): IndexDropResponse {
    return IndexDropResponseFromJSONTyped(json, false);
}

export function IndexDropResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexDropResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dropped': json['dropped'],
    };
}

export function IndexDropResponseToJSON(value?: IndexDropResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dropped': value.dropped,
    };
}

