/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IndexOptionsRequest } from './IndexOptionsRequest';
import {
    IndexOptionsRequestFromJSON,
    IndexOptionsRequestFromJSONTyped,
    IndexOptionsRequestToJSON,
} from './IndexOptionsRequest';

/**
 * 
 * @export
 * @interface IndexCreateRequest
 */
export interface IndexCreateRequest {
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof IndexCreateRequest
     */
    keys: { [key: string]: number; } | null;
    /**
     * 
     * @type {IndexOptionsRequest}
     * @memberof IndexCreateRequest
     */
    indexOptionsRequest?: IndexOptionsRequest;
}

/**
 * Check if a given object implements the IndexCreateRequest interface.
 */
export function instanceOfIndexCreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "keys" in value;

    return isInstance;
}

export function IndexCreateRequestFromJSON(json: any): IndexCreateRequest {
    return IndexCreateRequestFromJSONTyped(json, false);
}

export function IndexCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keys': json['keys'],
        'indexOptionsRequest': !exists(json, 'indexOptionsRequest') ? undefined : IndexOptionsRequestFromJSON(json['indexOptionsRequest']),
    };
}

export function IndexCreateRequestToJSON(value?: IndexCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'keys': value.keys,
        'indexOptionsRequest': IndexOptionsRequestToJSON(value.indexOptionsRequest),
    };
}

