/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndexCreateResponse
 */
export interface IndexCreateResponse {
    /**
     * 
     * @type {string}
     * @memberof IndexCreateResponse
     */
    name: string;
}

/**
 * Check if a given object implements the IndexCreateResponse interface.
 */
export function instanceOfIndexCreateResponse(value: object): value is IndexCreateResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function IndexCreateResponseFromJSON(json: any): IndexCreateResponse {
    return IndexCreateResponseFromJSONTyped(json, false);
}

export function IndexCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function IndexCreateResponseToJSON(json: any): IndexCreateResponse {
    return IndexCreateResponseToJSONTyped(json, false);
}

export function IndexCreateResponseToJSONTyped(value?: IndexCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

