/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobConfig
 */
export interface JobConfig {
    /**
     * 
     * @type {string}
     * @memberof JobConfig
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof JobConfig
     */
    className: string;
    /**
     * 
     * @type {string}
     * @memberof JobConfig
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof JobConfig
     */
    cronExpression: string;
    /**
     * 
     * @type {string}
     * @memberof JobConfig
     */
    group: string;
    /**
     * 
     * @type {number}
     * @memberof JobConfig
     */
    priority: number;
}

export function JobConfigFromJSON(json: any): JobConfig {
    return JobConfigFromJSONTyped(json, false);
}

export function JobConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'className': json['className'],
        'description': json['description'],
        'cronExpression': json['cronExpression'],
        'group': json['group'],
        'priority': json['priority'],
    };
}

export function JobConfigToJSON(value?: JobConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'className': value.className,
        'description': value.description,
        'cronExpression': value.cronExpression,
        'group': value.group,
        'priority': value.priority,
    };
}

