/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JsonSchemaDefinition } from './JsonSchemaDefinition';
import {
    JsonSchemaDefinitionFromJSON,
    JsonSchemaDefinitionFromJSONTyped,
    JsonSchemaDefinitionToJSON,
} from './JsonSchemaDefinition';

/**
 * 
 * @export
 * @interface JsonSchema
 */
export interface JsonSchema {
    /**
     * 
     * @type {string}
     * @memberof JsonSchema
     */
    $schema: string;
    /**
     * 
     * @type {string}
     * @memberof JsonSchema
     */
    $ref: string;
    /**
     * 
     * @type {{ [key: string]: JsonSchemaDefinition; }}
     * @memberof JsonSchema
     */
    definitions: { [key: string]: JsonSchemaDefinition; };
}

/**
 * Check if a given object implements the JsonSchema interface.
 */
export function instanceOfJsonSchema(value: object): boolean {
    if (!('$schema' in value)) return false;
    if (!('$ref' in value)) return false;
    if (!('definitions' in value)) return false;
    return true;
}

export function JsonSchemaFromJSON(json: any): JsonSchema {
    return JsonSchemaFromJSONTyped(json, false);
}

export function JsonSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonSchema {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'],
        '$ref': json['$ref'],
        'definitions': json['definitions'],
    };
}

export function JsonSchemaToJSON(value?: JsonSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        '$schema': value['$schema'],
        '$ref': value['$ref'],
        'definitions': value['definitions'],
    };
}

