/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JsonSchemaDefinition
 */
export interface JsonSchemaDefinition {
    /**
     * 
     * @type {string}
     * @memberof JsonSchemaDefinition
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof JsonSchemaDefinition
     */
    title: string;
    /**
     * 
     * @type {boolean}
     * @memberof JsonSchemaDefinition
     */
    additionalProperties: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof JsonSchemaDefinition
     */
    required?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof JsonSchemaDefinition
     */
    properties: { [key: string]: { [key: string]: string; }; };
}

/**
 * Check if a given object implements the JsonSchemaDefinition interface.
 */
export function instanceOfJsonSchemaDefinition(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "additionalProperties" in value;
    isInstance = isInstance && "properties" in value;

    return isInstance;
}

export function JsonSchemaDefinitionFromJSON(json: any): JsonSchemaDefinition {
    return JsonSchemaDefinitionFromJSONTyped(json, false);
}

export function JsonSchemaDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonSchemaDefinition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'title': json['title'],
        'additionalProperties': json['additionalProperties'],
        'required': !exists(json, 'required') ? undefined : json['required'],
        'properties': json['properties'],
    };
}

export function JsonSchemaDefinitionToJSON(value?: JsonSchemaDefinition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'title': value.title,
        'additionalProperties': value.additionalProperties,
        'required': value.required,
        'properties': value.properties,
    };
}

