/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JsonValueAny
 */
export interface JsonValueAny {
    /**
     * 
     * @type {string}
     * @memberof JsonValueAny
     */
    value: string;
}

export function JsonValueAnyFromJSON(json: any): JsonValueAny {
    return JsonValueAnyFromJSONTyped(json, false);
}

export function JsonValueAnyFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonValueAny {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function JsonValueAnyToJSON(value?: JsonValueAny | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

