/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JsonResultString
 */
export interface JsonResultString {
    /**
     * 
     * @type {string}
     * @memberof JsonResultString
     */
    value: string;
}

export function JsonResultStringFromJSON(json: any): JsonResultString {
    return JsonResultStringFromJSONTyped(json, false);
}

export function JsonResultStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonResultString {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function JsonResultStringToJSON(value?: JsonResultString | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

