/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserProfile,
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
} from './UserProfile';

/**
 * 
 * @export
 * @interface LoginResult
 */
export interface LoginResult {
    /**
     * 
     * @type {string}
     * @memberof LoginResult
     */
    authToken: string;
    /**
     * 
     * @type {UserProfile}
     * @memberof LoginResult
     */
    userProfile: UserProfile;
    /**
     * 
     * @type {Date}
     * @memberof LoginResult
     */
    expirationDate: Date;
}

export function LoginResultFromJSON(json: any): LoginResult {
    return LoginResultFromJSONTyped(json, false);
}

export function LoginResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authToken': json['authToken'],
        'userProfile': UserProfileFromJSON(json['userProfile']),
        'expirationDate': (new Date(json['expirationDate'])),
    };
}

export function LoginResultToJSON(value?: LoginResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authToken': value.authToken,
        'userProfile': UserProfileToJSON(value.userProfile),
        'expirationDate': (value.expirationDate.toISOString()),
    };
}

