/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PipelineStage } from './PipelineStage';
import {
    PipelineStageFromJSON,
    PipelineStageFromJSONTyped,
    PipelineStageToJSON,
    PipelineStageToJSONTyped,
} from './PipelineStage';

/**
 * 
 * @export
 * @interface MongoAggregateRequest
 */
export interface MongoAggregateRequest {
    /**
     * 
     * @type {Array<PipelineStage>}
     * @memberof MongoAggregateRequest
     */
    pipeline?: Array<PipelineStage>;
    /**
     * 
     * @type {boolean}
     * @memberof MongoAggregateRequest
     */
    allowDiskUse: boolean;
}

/**
 * Check if a given object implements the MongoAggregateRequest interface.
 */
export function instanceOfMongoAggregateRequest(value: object): value is MongoAggregateRequest {
    if (!('allowDiskUse' in value) || value['allowDiskUse'] === undefined) return false;
    return true;
}

export function MongoAggregateRequestFromJSON(json: any): MongoAggregateRequest {
    return MongoAggregateRequestFromJSONTyped(json, false);
}

export function MongoAggregateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MongoAggregateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pipeline': json['pipeline'] == null ? undefined : ((json['pipeline'] as Array<any>).map(PipelineStageFromJSON)),
        'allowDiskUse': json['allowDiskUse'],
    };
}

  export function MongoAggregateRequestToJSON(json: any): MongoAggregateRequest {
      return MongoAggregateRequestToJSONTyped(json, false);
  }

  export function MongoAggregateRequestToJSONTyped(value?: MongoAggregateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pipeline': value['pipeline'] == null ? undefined : ((value['pipeline'] as Array<any>).map(PipelineStageToJSON)),
        'allowDiskUse': value['allowDiskUse'],
    };
}

