/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MongoFindRequest
 */
export interface MongoFindRequest {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MongoFindRequest
     */
    filter: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MongoFindRequest
     */
    sort: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MongoFindRequest
     */
    projection: { [key: string]: string; };
}

/**
 * Check if a given object implements the MongoFindRequest interface.
 */
export function instanceOfMongoFindRequest(value: object): value is MongoFindRequest {
    if (!('filter' in value) || value['filter'] === undefined) return false;
    if (!('sort' in value) || value['sort'] === undefined) return false;
    if (!('projection' in value) || value['projection'] === undefined) return false;
    return true;
}

export function MongoFindRequestFromJSON(json: any): MongoFindRequest {
    return MongoFindRequestFromJSONTyped(json, false);
}

export function MongoFindRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MongoFindRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'filter': json['filter'],
        'sort': json['sort'],
        'projection': json['projection'],
    };
}

export function MongoFindRequestToJSON(value?: MongoFindRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'filter': value['filter'],
        'sort': value['sort'],
        'projection': value['projection'],
    };
}

