/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MongoFindRequest
 */
export interface MongoFindRequest {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MongoFindRequest
     */
    filter: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MongoFindRequest
     */
    sort: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MongoFindRequest
     */
    projection: { [key: string]: string; };
}

export function MongoFindRequestFromJSON(json: any): MongoFindRequest {
    return MongoFindRequestFromJSONTyped(json, false);
}

export function MongoFindRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MongoFindRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'filter': json['filter'],
        'sort': json['sort'],
        'projection': json['projection'],
    };
}

export function MongoFindRequestToJSON(value?: MongoFindRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'filter': value.filter,
        'sort': value.sort,
        'projection': value.projection,
    };
}

