/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PipelineStage
 */
export interface PipelineStage {
    /**
     * 
     * @type {string}
     * @memberof PipelineStage
     */
    stage: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineStage
     */
    value: string;
}

/**
 * Check if a given object implements the PipelineStage interface.
 */
export function instanceOfPipelineStage(value: object): boolean {
    if (!('stage' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function PipelineStageFromJSON(json: any): PipelineStage {
    return PipelineStageFromJSONTyped(json, false);
}

export function PipelineStageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineStage {
    if (json == null) {
        return json;
    }
    return {
        
        'stage': json['stage'],
        'value': json['value'],
    };
}

export function PipelineStageToJSON(value?: PipelineStage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'stage': value['stage'],
        'value': value['value'],
    };
}

