/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SchemaAnalysisFieldType } from './SchemaAnalysisFieldType';
import {
    SchemaAnalysisFieldTypeFromJSON,
    SchemaAnalysisFieldTypeFromJSONTyped,
    SchemaAnalysisFieldTypeToJSON,
} from './SchemaAnalysisFieldType';

/**
 * 
 * @export
 * @interface SchemaAnalysisField
 */
export interface SchemaAnalysisField {
    /**
     * 
     * @type {string}
     * @memberof SchemaAnalysisField
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaAnalysisField
     */
    fullName: string;
    /**
     * 
     * @type {Array<SchemaAnalysisFieldType>}
     * @memberof SchemaAnalysisField
     */
    fieldTypes?: Array<SchemaAnalysisFieldType>;
    /**
     * 
     * @type {number}
     * @memberof SchemaAnalysisField
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof SchemaAnalysisField
     */
    percentageOfParent: number;
    /**
     * 
     * @type {Array<SchemaAnalysisField>}
     * @memberof SchemaAnalysisField
     */
    subFields?: Array<SchemaAnalysisField>;
}

/**
 * Check if a given object implements the SchemaAnalysisField interface.
 */
export function instanceOfSchemaAnalysisField(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "fullName" in value;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "percentageOfParent" in value;

    return isInstance;
}

export function SchemaAnalysisFieldFromJSON(json: any): SchemaAnalysisField {
    return SchemaAnalysisFieldFromJSONTyped(json, false);
}

export function SchemaAnalysisFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaAnalysisField {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'fullName': json['fullName'],
        'fieldTypes': !exists(json, 'fieldTypes') ? undefined : ((json['fieldTypes'] as Array<any>).map(SchemaAnalysisFieldTypeFromJSON)),
        'count': json['count'],
        'percentageOfParent': json['percentageOfParent'],
        'subFields': !exists(json, 'subFields') ? undefined : ((json['subFields'] as Array<any>).map(SchemaAnalysisFieldFromJSON)),
    };
}

export function SchemaAnalysisFieldToJSON(value?: SchemaAnalysisField | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'fullName': value.fullName,
        'fieldTypes': value.fieldTypes === undefined ? undefined : ((value.fieldTypes as Array<any>).map(SchemaAnalysisFieldTypeToJSON)),
        'count': value.count,
        'percentageOfParent': value.percentageOfParent,
        'subFields': value.subFields === undefined ? undefined : ((value.subFields as Array<any>).map(SchemaAnalysisFieldToJSON)),
    };
}

