/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInformation
 */
export interface UserInformation {
    /**
     * 
     * @type {string}
     * @memberof UserInformation
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof UserInformation
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserInformation
     */
    apiKey?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserInformation
     */
    roles?: Array<string>;
}

/**
 * Check if a given object implements the UserInformation interface.
 */
export function instanceOfUserInformation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function UserInformationFromJSON(json: any): UserInformation {
    return UserInformationFromJSONTyped(json, false);
}

export function UserInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'password': json['password'],
        'apiKey': !exists(json, 'apiKey') ? undefined : json['apiKey'],
        'roles': !exists(json, 'roles') ? undefined : json['roles'],
    };
}

export function UserInformationToJSON(value?: UserInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'password': value.password,
        'apiKey': value.apiKey,
        'roles': value.roles,
    };
}

