/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInformation
 */
export interface UserInformation {
    /**
     * 
     * @type {string}
     * @memberof UserInformation
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof UserInformation
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserInformation
     */
    apiKey?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserInformation
     */
    roles?: Array<string>;
}

/**
 * Check if a given object implements the UserInformation interface.
 */
export function instanceOfUserInformation(value: object): boolean {
    if (!('userId' in value)) return false;
    if (!('password' in value)) return false;
    return true;
}

export function UserInformationFromJSON(json: any): UserInformation {
    return UserInformationFromJSONTyped(json, false);
}

export function UserInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInformation {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'password': json['password'],
        'apiKey': json['apiKey'] == null ? undefined : json['apiKey'],
        'roles': json['roles'] == null ? undefined : json['roles'],
    };
}

export function UserInformationToJSON(value?: UserInformation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'password': value['password'],
        'apiKey': value['apiKey'],
        'roles': value['roles'],
    };
}

