/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorDescription,
  JsonValueAny,
  JsonValueBoolean,
  MongoCampConfiguration,
  SettingsResponse,
} from '../models/index';
import {
    ErrorDescriptionFromJSON,
    ErrorDescriptionToJSON,
    JsonValueAnyFromJSON,
    JsonValueAnyToJSON,
    JsonValueBooleanFromJSON,
    JsonValueBooleanToJSON,
    MongoCampConfigurationFromJSON,
    MongoCampConfigurationToJSON,
    SettingsResponseFromJSON,
    SettingsResponseToJSON,
} from '../models/index';

export interface GetConfigRequest {
    configurationKey: string;
}

export interface ShutdownRequest {
    force?: boolean;
}

export interface UpdateConfigurationRequest {
    configurationKey: string;
    jsonValueAny: JsonValueAny;
}

/**
 * 
 */
export class ApplicationApi extends runtime.BaseAPI {

    /**
     * Creates request options for getConfig without sending the request
     */
    async getConfigRequestOpts(requestParameters: GetConfigRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['configurationKey'] == null) {
            throw new runtime.RequiredError(
                'configurationKey',
                'Required parameter "configurationKey" was null or undefined when calling getConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/system/configurations/{configurationKey}`;
        urlPath = urlPath.replace(`{${"configurationKey"}}`, encodeURIComponent(String(requestParameters['configurationKey'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Configuration for key
     * Configuration for configurationKey
     */
    async getConfigRaw(requestParameters: GetConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MongoCampConfiguration>> {
        const requestOptions = await this.getConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MongoCampConfigurationFromJSON(jsonValue));
    }

    /**
     * Get Configuration for key
     * Configuration for configurationKey
     */
    async getConfig(requestParameters: GetConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MongoCampConfiguration> {
        const response = await this.getConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listConfigurations without sending the request
     */
    async listConfigurationsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/system/configurations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all Configurations or filtered
     * List Configurations
     */
    async listConfigurationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MongoCampConfiguration>>> {
        const requestOptions = await this.listConfigurationsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MongoCampConfigurationFromJSON));
    }

    /**
     * List all Configurations or filtered
     * List Configurations
     */
    async listConfigurations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MongoCampConfiguration>> {
        const response = await this.listConfigurationsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for settings without sending the request
     */
    async settingsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/system/settings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the Settings of the running MongoCamp Application.
     * System Settings
     */
    async settingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SettingsResponse>> {
        const requestOptions = await this.settingsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingsResponseFromJSON(jsonValue));
    }

    /**
     * Returns the Settings of the running MongoCamp Application.
     * System Settings
     */
    async settings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SettingsResponse> {
        const response = await this.settingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for shutdown without sending the request
     */
    async shutdownRequestOpts(requestParameters: ShutdownRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/system`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Shutdown the running MongoCamp Application. CLI Mode will automatically restart the Application.
     * Shutdown MongoCamp
     */
    async shutdownRaw(requestParameters: ShutdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JsonValueBoolean>> {
        const requestOptions = await this.shutdownRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JsonValueBooleanFromJSON(jsonValue));
    }

    /**
     * Shutdown the running MongoCamp Application. CLI Mode will automatically restart the Application.
     * Shutdown MongoCamp
     */
    async shutdown(requestParameters: ShutdownRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JsonValueBoolean> {
        const response = await this.shutdownRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateConfiguration without sending the request
     */
    async updateConfigurationRequestOpts(requestParameters: UpdateConfigurationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['configurationKey'] == null) {
            throw new runtime.RequiredError(
                'configurationKey',
                'Required parameter "configurationKey" was null or undefined when calling updateConfiguration().'
            );
        }

        if (requestParameters['jsonValueAny'] == null) {
            throw new runtime.RequiredError(
                'jsonValueAny',
                'Required parameter "jsonValueAny" was null or undefined when calling updateConfiguration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/system/configurations/{configurationKey}`;
        urlPath = urlPath.replace(`{${"configurationKey"}}`, encodeURIComponent(String(requestParameters['configurationKey'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: JsonValueAnyToJSON(requestParameters['jsonValueAny']),
        };
    }

    /**
     * Update Configuration with the value
     * Update Configuration
     */
    async updateConfigurationRaw(requestParameters: UpdateConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JsonValueBoolean>> {
        const requestOptions = await this.updateConfigurationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JsonValueBooleanFromJSON(jsonValue));
    }

    /**
     * Update Configuration with the value
     * Update Configuration
     */
    async updateConfiguration(requestParameters: UpdateConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JsonValueBoolean> {
        const response = await this.updateConfigurationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
