/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionStatus,
  ErrorDescription,
  JsonSchema,
  JsonValueBoolean,
  MongoAggregateRequest,
  SchemaAnalysis,
} from '../models/index';
import {
    CollectionStatusFromJSON,
    CollectionStatusToJSON,
    ErrorDescriptionFromJSON,
    ErrorDescriptionToJSON,
    JsonSchemaFromJSON,
    JsonSchemaToJSON,
    JsonValueBooleanFromJSON,
    JsonValueBooleanToJSON,
    MongoAggregateRequestFromJSON,
    MongoAggregateRequestToJSON,
    SchemaAnalysisFromJSON,
    SchemaAnalysisToJSON,
} from '../models/index';

export interface AggregateRequest {
    collectionName: string;
    mongoAggregateRequest: MongoAggregateRequest;
    rowsPerPage?: number;
    page?: number;
}

export interface ClearCollectionRequest {
    collectionName: string;
}

export interface DeleteCollectionRequest {
    collectionName: string;
}

export interface DistinctRequest {
    collectionName: string;
    field: string;
    rowsPerPage?: number;
    page?: number;
}

export interface GetCollectionFieldsRequest {
    collectionName: string;
    sampleSize?: number;
}

export interface GetCollectionInformationRequest {
    collectionName: string;
    includeDetails?: boolean;
}

export interface GetJsonSchemaRequest {
    collectionName: string;
    sampleSize?: number;
    deepth?: number;
}

export interface GetSchemaAnalysisRequest {
    collectionName: string;
    sampleSize?: number;
    deepth?: number;
}

export interface ListCollectionsByDatabaseRequest {
    databaseName: string;
}

/**
 * 
 */
export class CollectionApi extends runtime.BaseAPI {

    /**
     * Creates request options for aggregate without sending the request
     */
    async aggregateRequestOpts(requestParameters: AggregateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling aggregate().'
            );
        }

        if (requestParameters['mongoAggregateRequest'] == null) {
            throw new runtime.RequiredError(
                'mongoAggregateRequest',
                'Required parameter "mongoAggregateRequest" was null or undefined when calling aggregate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['rowsPerPage'] != null) {
            queryParameters['rowsPerPage'] = requestParameters['rowsPerPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/collections/{collectionName}/aggregate`;
        urlPath = urlPath.replace(`{${"collectionName"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MongoAggregateRequestToJSON(requestParameters['mongoAggregateRequest']),
        };
    }

    /**
     * Aggregate in a given Collection
     * Aggregate in Collection
     */
    async aggregateRaw(requestParameters: AggregateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<{ [key: string]: string; }>>> {
        const requestOptions = await this.aggregateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Aggregate in a given Collection
     * Aggregate in Collection
     */
    async aggregate(requestParameters: AggregateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<{ [key: string]: string; }>> {
        const response = await this.aggregateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for clearCollection without sending the request
     */
    async clearCollectionRequestOpts(requestParameters: ClearCollectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling clearCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/collections/{collectionName}/clear`;
        urlPath = urlPath.replace(`{${"collectionName"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete all Document in Collection
     * Clear Collection
     */
    async clearCollectionRaw(requestParameters: ClearCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JsonValueBoolean>> {
        const requestOptions = await this.clearCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JsonValueBooleanFromJSON(jsonValue));
    }

    /**
     * Delete all Document in Collection
     * Clear Collection
     */
    async clearCollection(requestParameters: ClearCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JsonValueBoolean> {
        const response = await this.clearCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteCollection without sending the request
     */
    async deleteCollectionRequestOpts(requestParameters: DeleteCollectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling deleteCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/collections/{collectionName}`;
        urlPath = urlPath.replace(`{${"collectionName"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a given Collection
     * Delete Collection
     */
    async deleteCollectionRaw(requestParameters: DeleteCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JsonValueBoolean>> {
        const requestOptions = await this.deleteCollectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JsonValueBooleanFromJSON(jsonValue));
    }

    /**
     * Delete a given Collection
     * Delete Collection
     */
    async deleteCollection(requestParameters: DeleteCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JsonValueBoolean> {
        const response = await this.deleteCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for distinct without sending the request
     */
    async distinctRequestOpts(requestParameters: DistinctRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling distinct().'
            );
        }

        if (requestParameters['field'] == null) {
            throw new runtime.RequiredError(
                'field',
                'Required parameter "field" was null or undefined when calling distinct().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['rowsPerPage'] != null) {
            queryParameters['rowsPerPage'] = requestParameters['rowsPerPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/collections/{collectionName}/distinct/{field}`;
        urlPath = urlPath.replace(`{${"collectionName"}}`, encodeURIComponent(String(requestParameters['collectionName'])));
        urlPath = urlPath.replace(`{${"field"}}`, encodeURIComponent(String(requestParameters['field'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Distinct for Field in a given Collection
     * Distinct in Collection
     */
    async distinctRaw(requestParameters: DistinctRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.distinctRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Distinct for Field in a given Collection
     * Distinct in Collection
     */
    async distinct(requestParameters: DistinctRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.distinctRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCollectionFields without sending the request
     */
    async getCollectionFieldsRequestOpts(requestParameters: GetCollectionFieldsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling getCollectionFields().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sampleSize'] != null) {
            queryParameters['sample size'] = requestParameters['sampleSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/collections/{collectionName}/fields`;
        urlPath = urlPath.replace(`{${"collectionName"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the Fields in a given collection
     * Collection Fields
     */
    async getCollectionFieldsRaw(requestParameters: GetCollectionFieldsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.getCollectionFieldsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List the Fields in a given collection
     * Collection Fields
     */
    async getCollectionFields(requestParameters: GetCollectionFieldsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getCollectionFieldsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCollectionInformation without sending the request
     */
    async getCollectionInformationRequestOpts(requestParameters: GetCollectionInformationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling getCollectionInformation().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeDetails'] != null) {
            queryParameters['includeDetails'] = requestParameters['includeDetails'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/collections/{collectionName}`;
        urlPath = urlPath.replace(`{${"collectionName"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * All Information about a single Collection
     * Collection Information
     */
    async getCollectionInformationRaw(requestParameters: GetCollectionInformationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionStatus>> {
        const requestOptions = await this.getCollectionInformationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionStatusFromJSON(jsonValue));
    }

    /**
     * All Information about a single Collection
     * Collection Information
     */
    async getCollectionInformation(requestParameters: GetCollectionInformationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionStatus> {
        const response = await this.getCollectionInformationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getJsonSchema without sending the request
     */
    async getJsonSchemaRequestOpts(requestParameters: GetJsonSchemaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling getJsonSchema().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sampleSize'] != null) {
            queryParameters['sampleSize'] = requestParameters['sampleSize'];
        }

        if (requestParameters['deepth'] != null) {
            queryParameters['deepth'] = requestParameters['deepth'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/collections/{collectionName}/schema`;
        urlPath = urlPath.replace(`{${"collectionName"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the Fields in a given collection
     * Collection Fields
     */
    async getJsonSchemaRaw(requestParameters: GetJsonSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JsonSchema>> {
        const requestOptions = await this.getJsonSchemaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JsonSchemaFromJSON(jsonValue));
    }

    /**
     * List the Fields in a given collection
     * Collection Fields
     */
    async getJsonSchema(requestParameters: GetJsonSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JsonSchema> {
        const response = await this.getJsonSchemaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSchemaAnalysis without sending the request
     */
    async getSchemaAnalysisRequestOpts(requestParameters: GetSchemaAnalysisRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['collectionName'] == null) {
            throw new runtime.RequiredError(
                'collectionName',
                'Required parameter "collectionName" was null or undefined when calling getSchemaAnalysis().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sampleSize'] != null) {
            queryParameters['sampleSize'] = requestParameters['sampleSize'];
        }

        if (requestParameters['deepth'] != null) {
            queryParameters['deepth'] = requestParameters['deepth'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/collections/{collectionName}/schema/analysis`;
        urlPath = urlPath.replace(`{${"collectionName"}}`, encodeURIComponent(String(requestParameters['collectionName'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the Fields in a given collection
     * Collection Fields
     */
    async getSchemaAnalysisRaw(requestParameters: GetSchemaAnalysisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaAnalysis>> {
        const requestOptions = await this.getSchemaAnalysisRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaAnalysisFromJSON(jsonValue));
    }

    /**
     * List the Fields in a given collection
     * Collection Fields
     */
    async getSchemaAnalysis(requestParameters: GetSchemaAnalysisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaAnalysis> {
        const response = await this.getSchemaAnalysisRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCollections without sending the request
     */
    async listCollectionsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/collections`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List of all Collections of the default database
     * List of Collections
     */
    async listCollectionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.listCollectionsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List of all Collections of the default database
     * List of Collections
     */
    async listCollections(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listCollectionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCollectionsByDatabase without sending the request
     */
    async listCollectionsByDatabaseRequestOpts(requestParameters: ListCollectionsByDatabaseRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['databaseName'] == null) {
            throw new runtime.RequiredError(
                'databaseName',
                'Required parameter "databaseName" was null or undefined when calling listCollectionsByDatabase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/databases/{databaseName}/collections`;
        urlPath = urlPath.replace(`{${"databaseName"}}`, encodeURIComponent(String(requestParameters['databaseName'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List of all Collections of the given database
     * List of Collections
     */
    async listCollectionsByDatabaseRaw(requestParameters: ListCollectionsByDatabaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.listCollectionsByDatabaseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List of all Collections of the given database
     * List of Collections
     */
    async listCollectionsByDatabase(requestParameters: ListCollectionsByDatabaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listCollectionsByDatabaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
