/* tslint:disable */
/* eslint-disable */
/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteResponse,
  ErrorDescription,
  FileInformation,
  InsertResponse,
  MongoFindRequest,
  UpdateFileInformationRequest,
  UpdateResponse,
} from '../models/index';
import {
    DeleteResponseFromJSON,
    DeleteResponseToJSON,
    ErrorDescriptionFromJSON,
    ErrorDescriptionToJSON,
    FileInformationFromJSON,
    FileInformationToJSON,
    InsertResponseFromJSON,
    InsertResponseToJSON,
    MongoFindRequestFromJSON,
    MongoFindRequestToJSON,
    UpdateFileInformationRequestFromJSON,
    UpdateFileInformationRequestToJSON,
    UpdateResponseFromJSON,
    UpdateResponseToJSON,
} from '../models/index';

export interface DeleteFileRequest {
    bucketName: string;
    fileId: string;
}

export interface FindFilesRequest {
    bucketName: string;
    mongoFindRequest: MongoFindRequest;
    rowsPerPage?: number;
    page?: number;
}

export interface GetFileRequest {
    bucketName: string;
    fileId: string;
}

export interface GetFileInformationRequest {
    bucketName: string;
    fileId: string;
}

export interface InsertFileRequest {
    bucketName: string;
    file: Blob;
    metaData: string;
    fileName?: string;
}

export interface ListFilesRequest {
    bucketName: string;
    filter?: string;
    sort?: string;
    projection?: string;
    rowsPerPage?: number;
    page?: number;
}

export interface UpdateFileInformationOperationRequest {
    bucketName: string;
    fileId: string;
    updateFileInformationRequest: UpdateFileInformationRequest;
}

/**
 * 
 */
export class FileApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteFile without sending the request
     */
    async deleteFileRequestOpts(requestParameters: DeleteFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bucketName'] == null) {
            throw new runtime.RequiredError(
                'bucketName',
                'Required parameter "bucketName" was null or undefined when calling deleteFile().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling deleteFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/buckets/{bucketName}/files/{fileId}`;
        urlPath = urlPath.replace(`{${"bucketName"}}`, encodeURIComponent(String(requestParameters['bucketName'])));
        urlPath = urlPath.replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters['fileId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete one File from given Bucket
     * Delete File from Bucket
     */
    async deleteFileRaw(requestParameters: DeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteResponse>> {
        const requestOptions = await this.deleteFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteResponseFromJSON(jsonValue));
    }

    /**
     * Delete one File from given Bucket
     * Delete File from Bucket
     */
    async deleteFile(requestParameters: DeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteResponse> {
        const response = await this.deleteFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for findFiles without sending the request
     */
    async findFilesRequestOpts(requestParameters: FindFilesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bucketName'] == null) {
            throw new runtime.RequiredError(
                'bucketName',
                'Required parameter "bucketName" was null or undefined when calling findFiles().'
            );
        }

        if (requestParameters['mongoFindRequest'] == null) {
            throw new runtime.RequiredError(
                'mongoFindRequest',
                'Required parameter "mongoFindRequest" was null or undefined when calling findFiles().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['rowsPerPage'] != null) {
            queryParameters['rowsPerPage'] = requestParameters['rowsPerPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/buckets/{bucketName}/files`;
        urlPath = urlPath.replace(`{${"bucketName"}}`, encodeURIComponent(String(requestParameters['bucketName'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MongoFindRequestToJSON(requestParameters['mongoFindRequest']),
        };
    }

    /**
     * Alternative to GET Route for more complex queries and URL max. Length
     * Files in Bucket
     */
    async findFilesRaw(requestParameters: FindFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FileInformation>>> {
        const requestOptions = await this.findFilesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FileInformationFromJSON));
    }

    /**
     * Alternative to GET Route for more complex queries and URL max. Length
     * Files in Bucket
     */
    async findFiles(requestParameters: FindFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FileInformation>> {
        const response = await this.findFilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFile without sending the request
     */
    async getFileRequestOpts(requestParameters: GetFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bucketName'] == null) {
            throw new runtime.RequiredError(
                'bucketName',
                'Required parameter "bucketName" was null or undefined when calling getFile().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling getFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/buckets/{bucketName}/files/{fileId}/file`;
        urlPath = urlPath.replace(`{${"bucketName"}}`, encodeURIComponent(String(requestParameters['bucketName'])));
        urlPath = urlPath.replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters['fileId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get File from given Bucket
     * File from Bucket
     */
    async getFileRaw(requestParameters: GetFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.getFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Get File from given Bucket
     * File from Bucket
     */
    async getFile(requestParameters: GetFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFileInformation without sending the request
     */
    async getFileInformationRequestOpts(requestParameters: GetFileInformationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bucketName'] == null) {
            throw new runtime.RequiredError(
                'bucketName',
                'Required parameter "bucketName" was null or undefined when calling getFileInformation().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling getFileInformation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/buckets/{bucketName}/files/{fileId}`;
        urlPath = urlPath.replace(`{${"bucketName"}}`, encodeURIComponent(String(requestParameters['bucketName'])));
        urlPath = urlPath.replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters['fileId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one FileInformation from given Bucket
     * FileInformation from Bucket
     */
    async getFileInformationRaw(requestParameters: GetFileInformationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileInformation>> {
        const requestOptions = await this.getFileInformationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileInformationFromJSON(jsonValue));
    }

    /**
     * Get one FileInformation from given Bucket
     * FileInformation from Bucket
     */
    async getFileInformation(requestParameters: GetFileInformationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileInformation> {
        const response = await this.getFileInformationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for insertFile without sending the request
     */
    async insertFileRequestOpts(requestParameters: InsertFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bucketName'] == null) {
            throw new runtime.RequiredError(
                'bucketName',
                'Required parameter "bucketName" was null or undefined when calling insertFile().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling insertFile().'
            );
        }

        if (requestParameters['metaData'] == null) {
            throw new runtime.RequiredError(
                'metaData',
                'Required parameter "metaData" was null or undefined when calling insertFile().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fileName'] != null) {
            queryParameters['fileName'] = requestParameters['fileName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['metaData'] != null) {
            formParams.append('metaData', requestParameters['metaData'] as any);
        }


        let urlPath = `/mongodb/buckets/{bucketName}/files`;
        urlPath = urlPath.replace(`{${"bucketName"}}`, encodeURIComponent(String(requestParameters['bucketName'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Insert one File in given Bucket
     * Insert File
     */
    async insertFileRaw(requestParameters: InsertFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InsertResponse>> {
        const requestOptions = await this.insertFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InsertResponseFromJSON(jsonValue));
    }

    /**
     * Insert one File in given Bucket
     * Insert File
     */
    async insertFile(requestParameters: InsertFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InsertResponse> {
        const response = await this.insertFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listFiles without sending the request
     */
    async listFilesRequestOpts(requestParameters: ListFilesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bucketName'] == null) {
            throw new runtime.RequiredError(
                'bucketName',
                'Required parameter "bucketName" was null or undefined when calling listFiles().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['projection'] != null) {
            queryParameters['projection'] = requestParameters['projection'];
        }

        if (requestParameters['rowsPerPage'] != null) {
            queryParameters['rowsPerPage'] = requestParameters['rowsPerPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/buckets/{bucketName}/files`;
        urlPath = urlPath.replace(`{${"bucketName"}}`, encodeURIComponent(String(requestParameters['bucketName'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Files paginated from given Bucket
     * Files in Bucket
     */
    async listFilesRaw(requestParameters: ListFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FileInformation>>> {
        const requestOptions = await this.listFilesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FileInformationFromJSON));
    }

    /**
     * Get Files paginated from given Bucket
     * Files in Bucket
     */
    async listFiles(requestParameters: ListFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FileInformation>> {
        const response = await this.listFilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateFileInformation without sending the request
     */
    async updateFileInformationRequestOpts(requestParameters: UpdateFileInformationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bucketName'] == null) {
            throw new runtime.RequiredError(
                'bucketName',
                'Required parameter "bucketName" was null or undefined when calling updateFileInformation().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling updateFileInformation().'
            );
        }

        if (requestParameters['updateFileInformationRequest'] == null) {
            throw new runtime.RequiredError(
                'updateFileInformationRequest',
                'Required parameter "updateFileInformationRequest" was null or undefined when calling updateFileInformation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("httpAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-AUTH-APIKEY"] = await this.configuration.apiKey("X-AUTH-APIKEY"); // apiKeyAuth authentication
        }


        let urlPath = `/mongodb/buckets/{bucketName}/files/{fileId}`;
        urlPath = urlPath.replace(`{${"bucketName"}}`, encodeURIComponent(String(requestParameters['bucketName'])));
        urlPath = urlPath.replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters['fileId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateFileInformationRequestToJSON(requestParameters['updateFileInformationRequest']),
        };
    }

    /**
     * Replace MetaData and potential update FileName
     * Update FileInformation in Bucket
     */
    async updateFileInformationRaw(requestParameters: UpdateFileInformationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateResponse>> {
        const requestOptions = await this.updateFileInformationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateResponseFromJSON(jsonValue));
    }

    /**
     * Replace MetaData and potential update FileName
     * Update FileInformation in Bucket
     */
    async updateFileInformation(requestParameters: UpdateFileInformationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateResponse> {
        const response = await this.updateFileInformationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
